services:
  db:
    image: postgres:15-alpine
    container_name: anki_db
    restart: always
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: anki_pgadmin
    restart: always
    env_file:
      - .env.db
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  
  migrate:
    build:
      context: ..
      dockerfile: db/Dockerfile.migrate
    depends_on:
      - db
    env_file:
      - .env.db
    command: python db/scripts/migrate.py
    volumes:
      - ../db:/app/db
      - ../requirements.txt:/app/requirements.txt